# Generated by Django 3.2 on 2023-11-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231122_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PollTemplate',
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'default_related_name': 'poll_options', 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответа'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'default_related_name': 'votes', 'verbose_name': 'Голос', 'verbose_name_plural': 'Голоса'},
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=4, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_options', to='api.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='invitation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.invitationcode', verbose_name='Код идентификации'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.polloption', verbose_name='Вариант ответа'),
        ),
    ]
