# Generated by Django 4.1.13 on 2023-12-06 08:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231124_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.polloption', verbose_name='Вариант ответа'),
        ),
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Анонимный пользователь',
                'verbose_name_plural': 'Анонимные пользователи',
                'default_related_name': 'anon_users',
            },
        ),
        migrations.AlterField(
            model_name='vote',
            name='invitation_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.anonuser', verbose_name='Анонимный пользователь'),
        ),
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
